# Mouse mode
set -g mouse on
# Lower ESC key time repeat
set -s escape-time 0
# Fix colors in tmux
set -g default-terminal 'screen-256color'
set -ga terminal-overrides ",xterm-256color*:Tc"
# Status bar color
set status-style "bg=#8AC6F2" 
# Status bar text color
set status-fg black 

# Send prefix Ctrl + a
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# Use Alt-hjkl keys to switch panes / Works only in iTerm-2 (Alt = +ESC)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Prefix + h / l to switch windows
bind-key h previous-window
bind-key l next-window

# Set easier window split keys
bind-key | split-window -h
bind-key - split-window -v

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."
